// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xwrqkmorzjtkbobtedxk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inh3cnFrbW9yemp0a2JvYnRlZHhrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTEwMzE2MTIsImV4cCI6MjA2NjYwNzYxMn0.z_Q3uPw_byakzSOrW9D_0zl2jQLtMlI9Tzk0WFcG-mU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);